django/school/classroom/urls.py
from django.urls import path
from .views import (HomeView,
                   ThankYouView,
                   ContactFormView,
                   TeacherCreateView,
                   TeacherUpdateView,
                   TeacherDeleteView,
                   TeacherListView,
                   TeacherDetailView)

app_name = 'classroom'

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path("thank_you/", ThankYouView.as_view(), name='thank_you'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('teacher_update/<int:pk>', TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>', TeacherDeleteView.as_view()),
    path('list_teacher', TeacherListView.as_view(), name='list_teacher'),
    path('teacher_detail/<int:pk>', TeacherDetailView.as_view(), name='teacher_detail'),
]

django/school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

django/school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

django/school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

django/school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,
                                  FormView,
                                  CreateView,
                                  ListView,
                                  UpdateView,
                                  DeleteView,
                                  DetailView)
from classroom.forms import ContactForm
from .models import Teacher

# Create your views here.

class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # success URL ?
    success_url = reverse_lazy('classroom:thank_you')
    # what to do with form ?
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class TeacherCreateView(CreateView):
     # look for model_form.html (by default)
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy("classroom:thank_you")

class TeacherListView(ListView):
    # look for model_list.html (by default)
    model = Teacher
    queryset = Teacher.objects.order_by('first_name')
    context_object_name = 'teacher_list'

class TeacherDetailView(DetailView):
    # look for model_detail.html (by default)
    model = Teacher

class TeacherUpdateView(UpdateView):
    # SHARE model_form.html (by default)
    model = Teacher
    fields = ["first_name", "last_name"]
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    # Form --> Confirm Delete Button
    # look for model_confirm_delete.html (by default)
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')

django/school/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>
<form action="" method="post">
	{% csrf_token %} {{form.as_p}}
	<input type="submit" />
</form>

django/school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>
<ul>
	<li>
		<a href="{% url 'classroom:thank_you' %}">Thank You Page</a>
	</li>
	<li>
		<a href="{% url 'classroom:contact' %}">contact Page</a>
	</li>
	<li>
		<a href="{% url 'classroom:create_teacher' %}">Create New Teacher Page</a>
	</li>
	<li>
		<a href="{% url 'classroom:list_teacher' %}">List Teacher Page</a>
	</li>
</ul>

django/school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher ?</h1>
<p>{{teacher}}</p>
<form method="post">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" />
</form>

django/school/classroom/templates/classroom/teacher_detail.html
<h1>Detail View for a Teacher</h1>
<p>{{teacher}}</p>
<a href="{% url 'classroom:home' %}">Home Page</a>

django/school/classroom/templates/classroom/teacher_form.html
<h1>Teacher form</h1>
<form method="post">
	{% csrf_token %} {{form.as_p}}
	<input type="submit" />
</form>

django/school/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers (ListView)</h1>

<ul>
	{% for teacher in teacher_list %}
	<li>
		<a href="/classroom/teacher_detail/{{teacher.id}}">
			{{teacher.first_name}} {{teacher.last_name}}</a
		>
		<ul>
			<li>
				<a href="/classroom/teacher_update/{{teacher.id}}">update info</a>
				<a href="/classroom/teacher_delete/{{teacher.id}}">delete info</a>
			</li>
		</ul>
		<br />
	</li>
	{% endfor %}
</ul>

django/school/classroom/templates/classroom/thank_you.html
<h1>Thank You</h1>
<a href="{% url 'classroom:home' %}">Home Page</a>