django/my_site/my_app/urls.py
from django.urls import path
from . import views

# register the app namespace
app_name = "my_app"

urlpatterns = [
    path('', views.example_view, name='example'),
    path('variable/', views.variable_view, name='variable')
]

django/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('office/', include('office.urls'))
]

handler404 = 'my_site.views.my_custom_page_not_found_view'

django/my_site/office/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_patients, name='list_patients')
]

django/my_site/my_app/models.py
from django.db import models

# Create your models here.

django/my_site/office/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)])
    heartrate = models.IntegerField(default=60, validators=[MinValueValidator(1), MaxValueValidator(300)])

    def __str__(self):
        return f"{self.last_name}, {self.first_name} is {self.age} years old"

django/my_site/my_app/views.py
from django.shortcuts import render

# Create your views here.
def example_view(request):
    return render(request, 'my_app/example.html')

def variable_view(request):



    return render(request, 'my_app/variable.html')

django/my_site/my_site/views.py
from django.shortcuts import render

def my_custom_page_not_found_view(request,execption):

    return render(request, '404.html', status=404)

django/my_site/office/views.py
from django.shortcuts import render
from . import models

# Create your views here.
def list_patients(request):
    all_patients = models.Patient.objects.all()
    context_list = {'patients':all_patients}
    return render(request, 'office/list.html', context=context_list)

django/my_site/my_app/templates/my_app/example.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>EXAMPLE HTML TEMPLATE CONNECTED!</h1>
<h1>
	<a href="{% url 'my_app:variable' %}">CLICK ME TO GO TO VARIABLE</a>
</h1>
<img src="{% static 'my_app/django.jpg' %}" alt="django reinhart" />
{% endblock %}

django/my_site/my_app/templates/my_app/variable.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<h1>VARIABLE.HTML</h1>
		<h2><a href="{% url 'my_app:example'%}">GO BACK</a></h2>
	</body>
</html>

django/my_site/office/templates/office/list.html
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>office</title>
    </head>
    <body>
        <ul>
        {% for person in patients %}
            <li>{{ person.last_name }}</li>
        {% endfor %}
        </ul>
    </body>
</html>

django/my_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>base title</title>
	</head>
	<body>
		<h1>This is ABOVE THE BLOCK IN BASE.html</h1>
		{% block content %} {% endblock content %}
		<h1>This is BELOW THE BLOCK IN BASE.html</h1>
	</body>
</html>