django/my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/',views.list,name='list'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),
]

django/my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cars/", include('cars.urls'))
]

django/my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

django/my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars':all_cars}
    return render(request, 'cars/list.html', context=context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        # if user submitted new car ----> List.html
        return redirect(reverse('cars:list'))
    return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        # delete the car
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('pk not found!')
            return redirect(reverse('cars:list'))
    return render(request, 'cars/delete.html')

django/my_car_site/cars/templates/cars/add.html
{% extends 'base.html' %} {% block content %}
<div class="container">
	<h1>ADD.HTML</h1>
	<h2>Add a new car to the database:</h2>
	<form action="" method="POST">
		{% csrf_token %}
		<div class="mb-3">
			<label for="brand" class="form-label">Brand:</label>
			<input id="brand" class="form-control" name="brand" type="text" />
		</div>
		<div class="mb-3">
			<label for="year" class="form-label">Year:</label>
			<input id="year" class="form-control" name="year" type="text" />
		</div>
		<input type="submit" class="btn btn-primary mb-3" />
	</form>
</div>
{% endblock content %}

django/my_car_site/cars/templates/cars/delete.html
{% extends 'base.html' %} {% block content %}
<div class="container">
	<h1>DELETE.HTML</h1>
	<h2>Enter pk to delete car!</h2>
	<form action="" method="POST">
		{% csrf_token %}
		<div class="mb-3">
			<label for="pk" class="form-label">PK Number:</label>
			<input type="text" class="form-control" id="pk" name="pk" />
		</div>
		<input type="submit" class="btn btn-primary mb-3" />
	</form>
</div>
{% endblock content %}

django/my_car_site/cars/templates/cars/list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h1>LIST.HTML</h1>
    <ul>
        {% for car in all_cars %}
            <li>{{car}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

django/my_car_site/templates/base.html
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <title>Cars</title>
    </head>
    <body>
{% comment %} NAVBAR {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% block content %}
{% endblock content %}
    </body>
</html>